output "resource_group_name" {
  value = azurerm_resource_group.this.name
}

output "aks_cluster_name" {
  value = azurerm_kubernetes_cluster.this.name
}

output "kube_config" {
  description = "Raw kubeconfig for the AKS cluster. Pipe to a file and use with kubectl/helm, e.g. `terraform output -raw kube_config > kubeconfig`."
  value       = azurerm_kubernetes_cluster.this.kube_config_raw
  sensitive   = true
}

output "node_pools" {
  description = "Tenant workload node pool names and the tier label used to schedule onto them."
  value = {
    small = azurerm_kubernetes_cluster_node_pool.small.name
    large = azurerm_kubernetes_cluster_node_pool.large.name
  }
}

output "key_vault_name" {
  value = azurerm_key_vault.this.name
}

output "neo4j_namespace" {
  value = kubernetes_namespace.neo4j.metadata[0].name
}

output "neo4j_cluster_size" {
  description = "Number of Neo4j cluster members deployed (neo4j_cluster_size)."
  value       = var.neo4j_cluster_size
}

output "neo4j_release_names" {
  description = "Helm release name for each Neo4j cluster member, regardless of neo4j_deployment_method. All members share neo4j.name (var.neo4j_release_name) and are selectable together via the label helm.neo4j.com/neo4j.name=<neo4j_release_name>."
  value       = values(local.neo4j_release_names)
}

output "neo4j_deployment_method" {
  description = "Which mechanism deployed the Neo4j release(s): \"helm_release\" (Terraform's native resource) or \"helm_cli\" (null_resource + local helm CLI)."
  value       = var.neo4j_deployment_method
}

output "neo4j_initial_password" {
  description = "Password for the neo4j user, generated by this stack and passed to the chart. Also stored in Key Vault as \"neo4j-admin-password\"."
  value       = random_password.neo4j.result
  sensitive   = true
}

output "neo4j_oidc_configured" {
  description = "Whether OIDC/Entra auth config was applied to the Neo4j release (true once var.neo4j_oidc_client_id is set)."
  value       = var.neo4j_oidc_client_id != ""
}

output "neo4j_authentication_providers" {
  description = "The literal dbms.security.authentication_providers value applied -- \"oidc-azure,native\" (both), \"oidc-azure\" (native disabled, var.neo4j_disable_native_auth = true), or unset if OIDC isn't configured at all yet."
  value       = var.neo4j_oidc_client_id != "" ? local.neo4j_authentication_providers : null
}

output "neo4j_pipeline_client_secret_stored" {
  description = "Whether var.neo4j_pipeline_client_secret was supplied and stored in Key Vault as neo4j-pipeline-client-secret."
  value       = var.neo4j_pipeline_client_secret != ""
}

output "neo4j_istio_gateway_enabled" {
  description = "Whether the Istio Gateway/VirtualService fronting Neo4j were deployed (var.neo4j_istio_gateway_enabled)."
  value       = var.neo4j_istio_gateway_enabled
}
