output "neo4j_namespace" {
  value = kubernetes_namespace.neo4j.metadata[0].name
}

output "neo4j_release_names" {
  description = "Helm release name for each Neo4j cluster member. All members share neo4j.name (var.neo4j_release_name)."
  value       = values(local.neo4j_release_names)
}

output "neo4j_initial_password" {
  description = "Password for the neo4j user, generated by this example and passed to the chart."
  value       = random_password.neo4j.result
  sensitive   = true
}

output "istio_gateway_enabled" {
  value = var.istio_gateway_enabled
}
